#############################################################################
# Makefile for building: chassis_test_001
# Generated by qmake (2.01a) (Qt 4.8.1) on: Mon Apr 3 10:48:09 2017
# Project:  chassis_test_001.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile chassis_test_001.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Iinclude -I/opt/etherlab/include -I/usr/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu /opt/etherlab/lib/libethercat.a /usr/lib/x86_64-linux-gnu/libpthread.so -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = source/Bezier.cpp \
		source/class_mobile_chassis.cpp \
		source/class_servo_motor.cpp \
		source/speed_planning.cpp \
		source/PID.cpp \
		source/ethercat_init.cpp \
		chassis.cpp \
		chassis_display.cpp moc_chassis_display.cpp
OBJECTS       = Bezier.o \
		class_mobile_chassis.o \
		class_servo_motor.o \
		speed_planning.o \
		PID.o \
		ethercat_init.o \
		chassis.o \
		chassis_display.o \
		moc_chassis_display.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		chassis_test_001.pro
QMAKE_TARGET  = chassis_test_001
DESTDIR       = 
TARGET        = chassis_test_001

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_chassis_display.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: chassis_test_001.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile chassis_test_001.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile chassis_test_001.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/chassis_test_0011.0.0 || $(MKDIR) .tmp/chassis_test_0011.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/chassis_test_0011.0.0/ && $(COPY_FILE) --parents include/Bezier.h include/class_mobile_chassis.h include/class_servo_motor.h include/my_chassis_init.h include/MyTypedef.h include/PID.h include/speed_planning.h include/ethercat_init.h chassis_display.h .tmp/chassis_test_0011.0.0/ && $(COPY_FILE) --parents source/Bezier.cpp source/class_mobile_chassis.cpp source/class_servo_motor.cpp source/speed_planning.cpp source/PID.cpp source/ethercat_init.cpp chassis.cpp chassis_display.cpp .tmp/chassis_test_0011.0.0/ && $(COPY_FILE) --parents chassis_display.ui .tmp/chassis_test_0011.0.0/ && (cd `dirname .tmp/chassis_test_0011.0.0` && $(TAR) chassis_test_0011.0.0.tar chassis_test_0011.0.0 && $(COMPRESS) chassis_test_0011.0.0.tar) && $(MOVE) `dirname .tmp/chassis_test_0011.0.0`/chassis_test_0011.0.0.tar.gz . && $(DEL_FILE) -r .tmp/chassis_test_0011.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_chassis_display.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_chassis_display.cpp
moc_chassis_display.cpp: chassis_display.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) chassis_display.h -o moc_chassis_display.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_chassis_display.h
compiler_uic_clean:
	-$(DEL_FILE) ui_chassis_display.h
ui_chassis_display.h: chassis_display.ui
	/usr/bin/uic-qt4 chassis_display.ui -o ui_chassis_display.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

Bezier.o: source/Bezier.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Bezier.o source/Bezier.cpp

class_mobile_chassis.o: source/class_mobile_chassis.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o class_mobile_chassis.o source/class_mobile_chassis.cpp

class_servo_motor.o: source/class_servo_motor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o class_servo_motor.o source/class_servo_motor.cpp

speed_planning.o: source/speed_planning.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speed_planning.o source/speed_planning.cpp

PID.o: source/PID.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PID.o source/PID.cpp

ethercat_init.o: source/ethercat_init.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ethercat_init.o source/ethercat_init.cpp

chassis.o: chassis.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chassis.o chassis.cpp

chassis_display.o: chassis_display.cpp chassis_display.h \
		ui_chassis_display.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chassis_display.o chassis_display.cpp

moc_chassis_display.o: moc_chassis_display.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chassis_display.o moc_chassis_display.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

